import { useMemo, useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { FileJson, Keyboard, LockKeyhole, Upload } from "lucide-react";

type Profile = { channelId: number; name: string; description: string; systemPrompt: string; temperature: number; taskFocus: string };

type Shortcut = { label: string; keys: string; detail: string };

const shortcuts: Shortcut[] = [
  { label: "เปิด command palette", keys: "Ctrl/Cmd + K", detail: "ค้นหาคำสั่งและไปยังเครื่องมือหลัก" },
  { label: "ส่งข้อความ", keys: "Enter", detail: "ส่งเมื่อไม่ได้อยู่ในโหมดขึ้นบรรทัดใหม่" },
  { label: "ขึ้นบรรทัดใหม่", keys: "Shift + Enter", detail: "เขียนคำสั่งหลายบรรทัดโดยไม่ส่งทันที" },
  { label: "ปิดหน้าต่าง", keys: "Esc", detail: "ปิด dialog หรือ palette ที่กำลังเปิด" },
];

export function ProfileImportPanel({ channels, profiles, profile, setProfile, onSaveProfile, onImport, importInputRef, onExport, exportReady, onDownload }: any) {
  const selectedProfile = profiles?.find((item: any) => item.id === profile.id);
  const activeChannelId = profile.channelId || channels?.[0]?.id || 0;
  return <div className="mt-5 grid gap-5 xl:grid-cols-[1.2fr_.8fr]">
    <section className="rounded-2xl border border-white/8 bg-white/[0.025] p-5">
      <div className="mb-4 flex items-start justify-between gap-3"><div><h2 className="text-sm font-semibold text-slate-100">โปรไฟล์การตอบ</h2><p className="mt-1 text-xs text-slate-500">กำหนดบทบาท ระบบคำสั่ง และอุณหภูมิแยกต่อ channel โดยไม่เก็บ credential</p></div><Badge variant="outline" className="border-cyan-300/20 text-cyan-100"><LockKeyhole className="mr-1 size-3" />ปลอดภัย</Badge></div>
      <div className="grid gap-3 sm:grid-cols-2"><select value={activeChannelId} onChange={event => setProfile({ ...profile, channelId: Number(event.target.value) })} className="h-9 rounded-lg border border-white/10 bg-white/[0.035] px-3 text-xs text-slate-300"><option value={0}>เลือก channel</option>{channels?.map((item: any) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><Input value={profile.name} onChange={event => setProfile({ ...profile, name: event.target.value })} placeholder="ชื่อโปรไฟล์" className="border-white/10 bg-white/[0.035]" /></div>
      <div className="mt-3 grid gap-3 sm:grid-cols-2"><Input value={profile.taskFocus} onChange={event => setProfile({ ...profile, taskFocus: event.target.value })} placeholder="งานหลัก เช่น development" className="border-white/10 bg-white/[0.035]" /><label className="rounded-lg border border-white/10 bg-white/[0.035] px-3 py-2 text-[11px] text-slate-400">Temperature: <span className="font-semibold text-cyan-100">{profile.temperature}%</span><input aria-label="temperature" type="range" min={0} max={100} value={profile.temperature} onChange={event => setProfile({ ...profile, temperature: Number(event.target.value) })} className="mt-2 w-full accent-cyan-300" /></label></div>
      <Input value={profile.description} onChange={event => setProfile({ ...profile, description: event.target.value })} placeholder="คำอธิบายโปรไฟล์" className="mt-3 border-white/10 bg-white/[0.035]" /><Textarea value={profile.systemPrompt} onChange={event => setProfile({ ...profile, systemPrompt: event.target.value })} placeholder="System prompt สำหรับโปรไฟล์นี้" className="mt-3 min-h-24 border-white/10 bg-white/[0.035]" /><Button disabled={!activeChannelId || profile.name.trim().length < 2 || !profile.taskFocus.trim()} onClick={() => onSaveProfile({ ...profile, channelId: activeChannelId, name: profile.name.trim(), description: profile.description || undefined, systemPrompt: profile.systemPrompt || undefined })} className="mt-3 w-full bg-cyan-300 text-slate-950 hover:bg-cyan-200">{selectedProfile ? "บันทึกโปรไฟล์ที่เลือก" : "สร้างโปรไฟล์ใหม่"}</Button>
    </section>
    <section className="rounded-2xl border border-white/8 bg-white/[0.025] p-5"><h2 className="text-sm font-semibold text-slate-100">เปรียบเทียบโปรไฟล์</h2><p className="mt-1 text-xs leading-5 text-slate-500">เปรียบเทียบหลายโปรไฟล์และแก้คำอธิบายได้จากตารางนี้</p><div className="mt-3 overflow-x-auto"><table className="w-full min-w-[620px] text-left text-[11px]"><thead className="border-b border-white/8 text-slate-500"><tr><th className="px-2 py-2 font-medium">ชื่อโปรไฟล์</th><th className="px-2 py-2 font-medium">งานหลัก</th><th className="px-2 py-2 font-medium">Temperature</th><th className="px-2 py-2 font-medium">คำอธิบาย</th><th className="px-2 py-2 font-medium">Channel</th></tr></thead><tbody>{profiles?.map((item: any) => <tr key={item.id} className="border-b border-white/5"><td className="px-2 py-2"><button onClick={() => setProfile({ id: item.id, channelId: item.channelId, name: item.name, description: item.description ?? "", systemPrompt: item.systemPrompt ?? "", temperature: item.temperature, taskFocus: item.taskFocus })} className="text-left font-medium text-cyan-100 hover:text-white">{item.name}</button></td><td className="px-2 py-2 text-slate-400">{item.taskFocus}</td><td className="px-2 py-2"><Badge variant="outline" className="border-cyan-300/20 text-[9px] text-cyan-100">{item.temperature}%</Badge></td><td className="px-2 py-2"><Input defaultValue={item.description ?? ""} aria-label={`คำอธิบาย ${item.name}`} onBlur={event => onSaveProfile({ id: item.id, channelId: item.channelId, name: item.name, description: event.target.value, systemPrompt: item.systemPrompt ?? undefined, temperature: item.temperature, taskFocus: item.taskFocus })} className="h-7 min-w-44 border-white/10 bg-white/[0.035] text-[10px]" /></td><td className="px-2 py-2 text-slate-500">#{item.channelId}</td></tr>)}</tbody></table>{!profiles?.length && <p className="py-4 text-center text-xs text-slate-600">ยังไม่มีโปรไฟล์</p>}</div></section><section className="rounded-2xl border border-white/8 bg-white/[0.025] p-5"><h2 className="text-sm font-semibold text-slate-100">นำเข้า / ส่งออก settings</h2><p className="mt-1 text-xs leading-5 text-slate-500">ตรวจ JSON ก่อนบันทึก และไม่รับ API key หรือ token จากไฟล์</p><input ref={importInputRef} type="file" accept="application/json,.json" className="hidden" onChange={event => { const file = event.target.files?.[0]; if (file) onImport(file); event.currentTarget.value = ""; }} /><div className="mt-4 grid gap-2"><Button variant="outline" onClick={() => importInputRef.current?.click()} className="border-white/10 bg-white/[0.035] text-slate-200"><Upload className="mr-2 size-4" />นำเข้า JSON settings</Button><Button variant="outline" onClick={onExport} className="border-white/10 bg-white/[0.035] text-slate-200"><FileJson className="mr-2 size-4" />เตรียมไฟล์ส่งออก</Button>{exportReady && <Button onClick={onDownload} className="bg-violet-300 text-slate-950 hover:bg-violet-200">ดาวน์โหลด JSON + .env.example</Button>}</div></section>
  </div>;
}

export function SkillRequirements({ category }: { category: string }) {
  const permissions = category === "development" || category === "database" ? ["อ่านไฟล์โครงการ"] : ["อ่านข้อความที่เลือก"];
  const dependency = category === "development" || category === "frontend" ? "ต้องมีไฟล์โครงการ" : "ไม่ต้องใช้ dependency เพิ่ม";
  return <div className="mt-2 flex flex-wrap gap-1.5 text-[9px]"><Badge variant="outline" className="border-amber-300/20 text-amber-100">สิทธิ์: {permissions.join(", ")}</Badge><Badge variant="outline" className="border-emerald-300/20 text-emerald-100">dependency: {dependency}</Badge></div>;
}

export function ShortcutBrowser() {
  const [query, setQuery] = useState("");
  const filtered = useMemo(() => shortcuts.filter(item => `${item.label} ${item.keys} ${item.detail}`.toLowerCase().includes(query.toLowerCase())), [query]);
  return <section className="mt-5 rounded-2xl border border-white/8 bg-white/[0.025] p-5"><div className="flex items-center gap-2"><Keyboard className="size-4 text-cyan-200" /><div><h2 className="text-sm font-semibold text-slate-100">รายการคีย์ลัด</h2><p className="mt-1 text-xs text-slate-500">ค้นหาคีย์ลัดที่ใช้ใน workspace และ command palette</p></div></div><Input value={query} onChange={event => setQuery(event.target.value)} placeholder="ค้นหาชื่อคำสั่งหรือปุ่ม" className="mt-4 border-white/10 bg-white/[0.035]" /><div className="mt-3 grid gap-2 sm:grid-cols-2">{filtered.map(item => <div key={item.label} className="rounded-xl border border-white/8 bg-black/10 p-3"><div className="flex items-center justify-between gap-2"><span className="text-xs text-slate-200">{item.label}</span><kbd className="rounded border border-cyan-300/20 bg-cyan-300/10 px-1.5 py-0.5 text-[10px] text-cyan-100">{item.keys}</kbd></div><p className="mt-1 text-[11px] text-slate-500">{item.detail}</p></div>)}{!filtered.length && <p className="text-xs text-slate-600">ไม่พบคีย์ลัดที่ตรงกัน</p>}</div></section>;
}
